stages:
  - build_macos
  - test_macos

build_macos:
  stage: build_macos
  script:
    - xcodebuild -project Perception.xcodeproj -scheme Perception clean build | xcpretty
  tags:
    - xcode
    - macos

test_macos:
  stage: test_macos
  script:
   - xcodebuild -project Perception.xcodeproj -scheme Perception clean test | xcpretty
  tags:
    - xcode
    - macos
